title: halie-san / はりーさん
domain: haliesan.com
email: haliesan0x0@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  I'm halie-san/はりーさん, Japanese pumpkin.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://haliesan.com
show_downloads: false
google_analytics:
theme: jekyll-theme-modernist

